### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by electroheadfx** [slidevjs/themes#7]
Hey, I not success to get the default font from your theme, how activate it ?

**Comment by alexanderdavide** [comment]
The default font 'Helvetica Neue' actually [is not](https://fonts.google.com/?query=Helvetica+Neue) on Google Fonts. Since `slidev` pulls fonts from Google Fonts (see [docs](https://sli.dev/custom/fonts.html#fonts)), I assume this is the reason why it doesn't work.

As a workaround you could replace the font in the front matter with 'Roboto' which is quite similar:

```markdown
---
fonts:
  sans: 'Roboto'
theme: apple-basic
---
```

Though, I am wondering why 'Helvetica Neue' is working fine locally, at least in my case.
